version: '2'

volumes:
  solr:
  db:
  redis:
  app:
  assets:

networks:
  internal:

services:

  solr:
    image: solr:8.4
    ports:
      - 9983:8983
    command: 
      - bash
      - "-c"
      - "precreate-core spotlight /opt/solr/server/configsets/spotlightconf; exec solr -f"
    volumes:
      - .:/app
      - ./solr/conf:/opt/solr/server/configsets/spotlightconf
      - solr:/opt/solr/server/solr
    networks:
      internal:

  db:
    image: postgres:11.1
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

  base:
    image: digitalrepoireland/spotlight_base:latest
    build:
      context: .
      dockerfile: Dockerfile.base
    env_file:
      - .env

  app:
    build: .
    image: digitalrepoireland/spotlight:latest
    env_file:
      - .env
    environment:
      - IN_DOCKER=true
      - RAILS_LOG_TO_STDOUT=true
      - REDIS_HOST=redis
      - SECRET_KEY_BASE=asdf
      - SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER=sidekiq
      - SETTINGS__SOLR__URL=http://solr:8983/solr/spotlight
      - SOLR_URL=http://solr:8983/solr/spotlight
      - PASSENGER_APP_ENV=development
      - RAILS_ENV=development
    volumes:
      - /home/app/webapp/tmp
      - app:/home/app/webapp/tmp/uploads
      - assets:/home/app/webapp/public/assets
      - .:/home/app/webapp
    networks:
      internal:

  web:
    extends:
      service: app
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=dri-spotlight.docker
    depends_on:
      - db
      - solr
      - redis
      - chrome
      - db_migrate
      - create_admin
    expose:
      - 80
    ports:
      - 3000:80 # uncomment this if you dont use dory or another proxy

  workers:
    extends:
      service: app
    command: bundle exec sidekiq
    depends_on:
      - db
      - solr
      - redis
      - db_migrate

  db_migrate:
    extends:
      service: app
    command: bundle exec rails db:migrate
    depends_on:
      - db

  create_admin:
    extends:
      service: app
    command: bundle exec rake dri_spotlight:admin
    depends_on:
      - db_migrate

  redis:
    image: redis:3
    command: redis-server
    volumes:
      - redis:/data
    networks:
      internal:

  chrome:
    image: selenium/standalone-chrome:3.141
    networks:
      internal:
