login: &login
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'sqlite3' %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] || 'db/development.sqlite' %>
  pool: <%= ENV['DATABASE_POOL'] || ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *login

test:
  <<: *login
  database: <%= ENV['DATABASE_TEST_NAME'] || 'dri_spotlight_test' %>

staging:
  <<: *login

production:
  <<: *login
