login: &login
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'postgresql' %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] || 'dri_spotlight' %>
  pool: 50
  timeout: 5000

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite

test:
  <<: *login
  database: <%= ENV['DATABASE_TEST_NAME'] || 'dri_spotlight_test' %>

staging:
  <<: *login


production:
  <<: *login
